name 'libartifact'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Library cookbook for managing release artifacts.'
long_description 'Library cookbook for managing release artifacts.'
version '1.3.5'

supports 'ubuntu', '>= 12.04'
supports 'centos', '>= 6.4'
supports 'redhat', '>= 6.4'
supports 'aix'
supports 'solaris'

depends 'libarchive', '~> 0.6'
depends 'poise', '~> 2.2'
